config:
  credentials:
  - id: orviz-github-basic
    password_var: GIT_PASS_1
    type: username_password
    username_var: GIT_USER_1
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
sqa_criteria:
  QC.Doc:
    repos:
      this_repo:
        commands:
        - |
          yarn install --frozen-lockfile
        - |
          yarn build
        - |
          env GIT_USER=$GIT_USER_1 GIT_PASS=$GIT_PASS_1 /usr/local/bin/yarn deploy
        container: qc.doc_bumpy-thistle-lionfish
timeout: 5400
