config:
  credentials:
      - id: userpass_sqaaas_web
        username_var: GIT_USER
        password_var: GIT_PASSWORD

sqa_criteria:
  qc_doc:
    repos:
      doc-sqaaas:
        container: node
        commands:
          - > 
            env GIT_ASKPASS=/doc-sqaaas/.git_credential_helper.sh
            npm --prefix /doc-sqaaas run deploy-gh-page --
            --user="Diana M. Naranjo <dnaranjo@i3m.upv.es>"
            --repo=https://${GIT_USER}@github.com/eosc-synergy/doc-sqaaas