services:
  qc.doc_bumpy-thistle-lionfish:
    command: sleep 6000000
    build:
      context: .
      dockerfile: docker/Dockerfile.build
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
